spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/membership_db
    username: myuser
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  application:
    name: membership-service
